name: env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - attrs=21.4.0
  - blas=1.0
  - brotli=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - curl=7.80.0
  - cycler=0.11.0
  - dbus=1.13.18
  - double-conversion=3.1.5
  - eigen=3.3.9
  - embree=2.17.7
  - expat=2.4.4
  - ffmpeg=4.2.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - geos=3.8.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - imageio=2.16.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - jpeg=9d
  - jsoncpp=1.9.4
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libcurl=7.80.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglu=9.0.0
  - libgomp=9.3.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtheora=1.1.1
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libvorbis=1.3.7
  - libvpx=1.7.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - libzip=1.8.0
  - loguru=0.5.3
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.6
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openh264=2.1.1
  - openssl=1.1.1n
  - packaging=21.3
  - pcre=8.45
  - pillow=9.0.1
  - pip=21.2.4
  - pluggy=1.0.0
  - proj=6.2.1
  - py=1.11.0
  - pyembree=0.1.6
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pytest=7.1.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pyvista=0.33.3
  - qt=5.9.7
  - readline=8.1.2
  - rtree=0.9.7
  - scooby=0.5.12
  - setuptools=58.0.4
  - shapely=1.7.1
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.0
  - tbb=2021.5.0
  - tk=8.6.11
  - toml=0.10.2
  - tomli=1.2.2
  - tornado=6.1
  - trimesh=3.10.7
  - typing_extensions=4.1.1
  - tzdata=2021e
  - utfcpp=3.2.1
  - vtk=9.0.3
  - wheel=0.37.1
  - x264=1!157.20191217
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
