name: env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pyvista=0.34
  - pyembree=0.1.6
  - trimesh=3.11.2
  - rtree=1.0.0
  - pytest=7.1.1
  - matplotlib=3.4.3
  - shapely=1.7.1